<?php
/**
 * @file
 * taxonomy_and_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function taxonomy_and_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'רחובות',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '13ee4f61-8444-4259-9d88-01a988092e95',
    'language' => 'he',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'campus',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'נוף',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '29e34c90-b639-4d46-8cf2-63492c2984a4',
    'language' => 'he',
    'i18n_tsid' => 24,
    'vocabulary_machine_name' => 'art_style',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'קיר אומנותי',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '33310652-eef4-439f-8384-63038ee72bd8',
    'language' => 'he',
    'i18n_tsid' => 14,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'הדפס',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '410de1b2-c2ab-4ab4-a3e9-c0b815cc9c11',
    'language' => 'he',
    'i18n_tsid' => 10,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'הר הצופים',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '475bcaf3-cdb1-4d5d-a195-1934df37329b',
    'language' => 'he',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'campus',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'המכון הוטרינרי',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '5d9e0300-74f0-4e04-8fb3-7b7b5450e88a',
    'language' => 'he',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'campus',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'ציור',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6cc56b25-dd78-4e85-8f44-713ed22f6878',
    'language' => 'he',
    'i18n_tsid' => 8,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'עין כרם',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '85ef4c4e-6244-43af-80dc-050501b08592',
    'language' => 'he',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'campus',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'רישום',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '89b80c8b-b7d9-4b80-a44a-ba77493fb60f',
    'language' => 'he',
    'i18n_tsid' => 6,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'חוץ',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8ad85996-db23-45b8-a500-dd210ec9b693',
    'language' => 'he',
    'i18n_tsid' => 28,
    'vocabulary_machine_name' => 'location',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'אחר',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8d29ad3a-ab85-461a-a5fb-16c5af3f1756',
    'language' => 'he',
    'i18n_tsid' => 16,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'תמונה',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '8e11e86b-9d5d-42c7-81d1-bb2dd64252ae',
    'language' => 'he',
    'i18n_tsid' => 4,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'לא בתצוגה',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '99c86552-15aa-4d27-9fc3-879c9d60f436',
    'language' => 'he',
    'i18n_tsid' => 30,
    'vocabulary_machine_name' => 'location',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'לא בתצוגה',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a4ca7701-aa4e-41cb-b6a0-ec7d698ea14a',
    'language' => 'he',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'campus',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'אדמונד י׳ ספרא',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'a88c219f-f14b-4486-a963-28083a8eb85a',
    'language' => 'he',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'campus',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'פיגורטיבי',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'b8c087f7-2abc-475c-95dd-bc81bbab8e6f',
    'language' => 'he',
    'i18n_tsid' => 20,
    'vocabulary_machine_name' => 'art_style',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'תבליט',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c4f67dda-5477-44a6-8afe-fe501922fe13',
    'language' => 'he',
    'i18n_tsid' => 12,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'פורטריט',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd41f2fd7-b439-4ca0-8b70-9fe37781dcf3',
    'language' => 'he',
    'i18n_tsid' => 18,
    'vocabulary_machine_name' => 'art_style',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'פסל',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd62ac0f3-4c13-4f35-bcf8-a46f79c11d1c',
    'language' => 'he',
    'i18n_tsid' => 2,
    'vocabulary_machine_name' => 'art_type',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'פנים',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'dc5b41fc-5adc-4a60-a99d-e6932bb6de0c',
    'language' => 'he',
    'i18n_tsid' => 26,
    'vocabulary_machine_name' => 'location',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'אבסטרקטי',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'f2bf1169-9358-4356-9628-5e0b145c0e6a',
    'language' => 'he',
    'i18n_tsid' => 22,
    'vocabulary_machine_name' => 'art_style',
    'metatags' => array(),
  );
  return $terms;
}
